import mongoose from "mongoose";
//Test Schema
// A Test is one API test case. It stores both the original plain
// English input from the user AND the AI-generated HTTP test config.
// Tests belong to a Project and optionally to a Suite.

const TestSchema = new mongoose.Schema(
  {
    //Ownership
    projectId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Project",
      required: true,
      index: true,
    },

    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // Optional: which suite this test belongs to
    suiteId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "TestSuite",
      default: null,
      index: true,
    },

    // Human Input
    // The original plain English description the user typed
    // e.g. "test if login fails with wrong password"
    name: {
      type: String,
      required: [true, "Test name is required"],
      trim: true,
      maxlength: [120, "Test name cannot exceed 120 characters"],
    },

    userInput: {
      type: String,
      required: true, // original plain English prompt
      trim: true,
    },

    // AI-Generated HTTP Test Config
    // Everything below is generated by Groq + LangChain RAG pipeline

    method: {
      type: String,
      required: true,
      enum: ["GET", "POST", "PUT", "PATCH", "DELETE"],
      uppercase: true,
    },
    // Params
    queryParams: {
      type: Map,
      of: String,
      default: {},
    },

    // Endpoint path only — base URL comes from Project
    // e.g. "/api/auth/login"  NOT "https://api.myapp.com/api/auth/login"
    url: {
      type: String,
      required: true,
      trim: true,
    },

    // HTTP headers to send with this request
    // e.g. { "Content-Type": "application/json", "x-custom": "value" }
    headers: {
      type: Map,
      of: String,
      default: {},
    },

    // Request body (null for GET/DELETE)
    body: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    // Assertions / Expectations
    expectedStatus: {
      type: Number,
      required: true,
      // e.g. 200, 201, 400, 401, 404
    },

    // Array of assertion strings the test runner evaluates
    // e.g. ["response.body.token exists", "response.body.user.email === 'test@test.com'"]
    assertions: {
      type: [String],
      default: [],
    },

    // RAG Metadata
    // Which endpoint chunks were retrieved from ChromaDB for this test?
    // Useful for debugging why AI generated a specific test
    ragContext: {
      type: [String], // array of retrieved endpoint chunk strings
      default: [],
      select: false, // don't return by default (can be large)
    },

    // AI Description
    // One-line human readable description generated by AI
    // e.g. "Tests that login returns 401 with invalid credentials"
    aiDescription: {
      type: String,
      default: null,
    },

    //  Conversation History (for refinement)
    // Stores multi-turn refinement chat so user can say
    // "also add a check for response time < 500ms"
    conversationHistory: {
      type: [
        {
          role: { type: String, enum: ["user", "assistant"] },
          content: { type: String },
          timestamp: { type: Date, default: Date.now },
        },
      ],
      default: [],
      select: false,
    },

    //  Last Run Summary (denormalized for test list view)
    lastRun: {
      status: {
        type: String,
        enum: ["pass", "fail", "error", "null"],
        default: null,
      },
      runAt: { type: Date, default: null },
      responseTime: { type: Number, default: null }, // ms
      isRegression: { type: Boolean, default: false },
    },

    // Flags
    isArchived: { type: Boolean, default: false },

    // Was this test manually edited in Monaco editor after AI generation?
    wasManuallyEdited: { type: Boolean, default: false },
    auth: {
      type: {
        type: String,
        enum: ["Bearer", "Basic", "API-Key", "None", "Inherit"],
        default: "Inherit",
      },
      token: { type: String, default: null },
      headerName: { type: String, default: null },
      captureAuthToken: { type: Boolean, default: false },
    },
  },
  {
    timestamps: true,
  },
);

// Indexes
TestSchema.index({ projectId: 1, createdAt: -1 });
TestSchema.index({ projectId: 1, "lastRun.status": 1 });
export default mongoose.model("Test", TestSchema);
