import mongoose from "mongoose";
//TestRun Schema
// A TestRun = one execution of a Test. Every time a test is run
// (individually or as part of a suite), a new TestRun document
// is created. This is the source of truth for run history,
// regression detection, and AI failure analysis.

const TestRunSchema = new mongoose.Schema(
  {
    //  Ownership
    testId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Test",
      required: true,
      index: true,
    },

    projectId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Project",
      required: true,
      index: true,
    },

    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },

    // If this run was triggered as part of a suite run
    suiteId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "TestSuite",
      default: null,
    },

    // Groups all tests that ran together in one "Run All" click
    // Same suiteRunId across multiple TestRun docs = same batch
    suiteRunId: {
      type: String,
      default: null,
      index: true,
    },

    //  What Was Sent 
    // Snapshot of the test config at time of run
    // (test may be edited later, this preserves the exact request made)
    requestSnapshot: {
      method:  { type: String },
      url:     { type: String },     // full URL including base
      headers: { type: mongoose.Schema.Types.Mixed },
      body:    { type: mongoose.Schema.Types.Mixed },
    },

    // Result 
    status: {
      type: String,
      enum: ["pass", "fail", "error"],
      // "pass"  → all assertions + status code passed
      // "fail"  → status or assertion mismatch
      // "error" → network error, timeout, CORS, etc.
      required: true,
    },

    // Actual HTTP status code returned by the API
    actualStatus: {
      type: Number,
      default: null,
    },

    // What the test expected vs what it got
    expectedStatus: {
      type: Number,
      required: true,
    },

    // Actual response body from the API
    actualBody: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },

    // Response time in milliseconds
    responseTime: {
      type: Number,
      default: null,
    },

    // Assertion Results 
    // Per-assertion pass/fail breakdown
    assertionResults: {
      type: [
        {
          assertion: { type: String },    // the assertion string
          passed:    { type: Boolean },   // did it pass?
          actual:    { type: String, default: null }, // actual value found
          error:     { type: String, default: null }, // error message if failed
        },
      ],
      default: [],
    },

    // Error Info (for status === "error") 
    // Network error, timeout, DNS failure etc.
    errorMessage: {
      type: String,
      default: null,
    },

    // Regression Detection 
    // true if this test was PASSING in the last run but FAILED now
    isRegression: {
      type: Boolean,
      default: false,
      index: true,
    },

    // Reference to the previous run used for regression comparison
    previousRunId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "TestRun",
      default: null,
    },

    //  AI Failure Analysis 
    // Only populated when status === "fail" or "error"
    // Generated by Gemini 1.5 Flash via LangChain
    aiAnalysis: {
      // Plain English explanation of what went wrong
      shortExplanation: { type: String, default: null },

      // Short suggested fix in plain English
      suggestedFix: { type: String, default: null },

      // Was AI analysis successfully generated?
      generated: { type: Boolean, default: false },

      // When was the analysis generated?
      generatedAt: { type: Date, default: null },
    },

    //  Triggered By 
    // How was this run triggered?
    triggeredBy: {
      type: String,
      enum: ["manual", "suite", "regression-check"],
      default: "manual",
    },

    // When exactly the run happened
    runAt: {
      type: Date,
      default: Date.now,
      index: true,
    },
  },
  {
    timestamps: true,
  }
);

//  Indexes 
// Fast lookup: all runs for a test ordered by time (for regression check)
TestRunSchema.index({ testId: 1, runAt: -1 });

// Fast lookup: all runs for a project (for dashboard + history)
TestRunSchema.index({ projectId: 1, runAt: -1 });

// Fast lookup: all regressions in a project
TestRunSchema.index({ projectId: 1, isRegression: 1, runAt: -1 });




export default mongoose.model("TestRun", TestRunSchema);